name: King_of_Hearts_Original_Names

on:
  schedule:
    - cron: '0 */4 * * *' # تحديث تلقائي كل 4 ساعات
  workflow_dispatch: # إمكانية التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Smart Filter and Base64 Encoding
        shell: python
        run: |
          import requests
          import base64
          import json
          import os

          # المصادر المطلوبة
          urls = [
              "https://raw.githubusercontent.com/miladtahanian/Config-Collector/main/mixed_iran.txt",
              "https://shz.al/~WangCai"
          ]
          
          def process():
              final_configs = []
              target_ports = [':443', ':80']
              vmess_ports = ['443', '80']

              for url in urls:
                  try:
                      response = requests.get(url, timeout=15)
                      if response.status_code == 200:
                          lines = response.text.splitlines()
                          for line in lines:
                              line = line.strip()
                              if not line: continue

                              # تصفية Trojan و Vless
                              if "trojan://" in line or
